import { useCallback, useEffect, useMemo, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { ApiError } from './api'
import { frequenciaApi, type AdolescenteResumo, type Encontro, type SituacaoEncontro, type SituacaoFrequencia } from './frequenciaApi'

interface Props { discipuladoId:number; podeAdministrar?:boolean }
interface ParticipanteChamada extends AdolescenteResumo { registroAnterior:boolean }
export default function FrequencyManagement({discipuladoId,podeAdministrar=false}:Props){
 const [encontros,setEncontros]=useState<Encontro[]>([]),[selecionado,setSelecionado]=useState<Encontro>(),[adolescentesAtuais,setAdolescentesAtuais]=useState<AdolescenteResumo[]>([]),[participantes,setParticipantes]=useState<ParticipanteChamada[]>([])
 const [chamada,setChamada]=useState<Record<number,SituacaoFrequencia>>({}),[data,setData]=useState(new Date().toISOString().slice(0,10)),[situacao,setSituacao]=useState<SituacaoEncontro>('REALIZADO')
 const [visitantes,setVisitantes]=useState(0),[erro,setErro]=useState(''),[sucesso,setSucesso]=useState(''),[carregando,setCarregando]=useState(false)
 const editavel=useMemo(()=>selecionado&&selecionado.situacao==='REALIZADO'&&(podeAdministrar||Date.now()<=new Date(selecionado.criadoEm).getTime()+3*60*60*1000),[selecionado,podeAdministrar])
 const carregar=useCallback(async()=>{const [novosEncontros,pagina]=await Promise.all([frequenciaApi.listarEncontros(discipuladoId),frequenciaApi.listarAdolescentes(discipuladoId)]);setEncontros(novosEncontros);setAdolescentesAtuais(pagina.content);return pagina.content},[discipuladoId])
 useEffect(()=>{setSelecionado(undefined);setParticipantes([]);setChamada({});setErro('');setSucesso('');void carregar().catch(e=>setErro(mensagem(e)))},[carregar])
 async function abrir(e:Encontro,atuais=adolescentesAtuais){setSelecionado(e);setVisitantes(0);setErro('');try{const existentes=await frequenciaApi.listarChamada(e.id);const idsAtuais=new Set(atuais.map(a=>a.id));const lista:ParticipanteChamada[]=[...atuais.map(a=>({...a,registroAnterior:false})),...existentes.filter(f=>!idsAtuais.has(f.adolescenteId)).map(f=>({id:f.adolescenteId,nome:f.adolescenteNome,registroAnterior:true}))];const mapa:Record<number,SituacaoFrequencia>={};lista.forEach(a=>mapa[a.id]='AUSENTE');existentes.forEach(f=>mapa[f.adolescenteId]=f.situacao);setParticipantes(lista);setChamada(mapa)}catch(x){setErro(mensagem(x));throw x}}
 async function criar(){setCarregando(true);setErro('');setSucesso('');try{const novo=await frequenciaApi.criarEncontro({discipuladoId,data,situacao});setSucesso('Encontro criado.');try{const atuais=await carregar();await abrir(novo,atuais)}catch{setSelecionado(novo);setErro('O encontro foi criado, mas não foi possível carregar a chamada. Selecione-o novamente para tentar de novo.')}}catch(e){setErro(mensagem(e))}finally{setCarregando(false)}}
 async function salvar(){if(!selecionado)return;setCarregando(true);setErro('');setSucesso('');try{await frequenciaApi.salvarChamada(selecionado.id,participantes.map(a=>({adolescenteId:a.id,situacao:chamada[a.id]??'AUSENTE'})));await frequenciaApi.salvarVisitantes(selecionado.id,visitantes);setSucesso('Chamada salva.')}catch(e){setErro(mensagem(e))}finally{setCarregando(false)}}
 return <Stack spacing={2}>
  <Typography variant="h5">Encontros e frequência</Typography>{erro&&<Alert severity="error">{erro}</Alert>}{sucesso&&<Alert severity="success">{sucesso}</Alert>}
  <Card><CardContent><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField label="Data" type="date" value={data} onChange={e=>setData(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><FormControl sx={{minWidth:180}}><InputLabel>Situação</InputLabel><Select label="Situação" value={situacao} onChange={e=>setSituacao(e.target.value as SituacaoEncontro)}><MenuItem value="REALIZADO">Realizado</MenuItem><MenuItem value="CANCELADO">Cancelado</MenuItem></Select></FormControl><Button variant="contained" onClick={criar} disabled={carregando}>Criar encontro</Button></Stack></CardContent></Card>
  <FormControl fullWidth><InputLabel>Encontro</InputLabel><Select label="Encontro" value={selecionado?.id??''} onChange={e=>{const item=encontros.find(x=>x.id===Number(e.target.value));if(item)void abrir(item).catch(()=>undefined)}}>{encontros.map(e=><MenuItem key={e.id} value={e.id}>{e.data} — {e.situacao}</MenuItem>)}</Select></FormControl>
  {selecionado&&<Card><CardContent><Stack spacing={1}>{!editavel&&<Alert severity="info">Chamada em modo somente leitura: encontro cancelado ou janela de três horas encerrada.</Alert>}{participantes.map(a=><Box key={a.id} display="flex" alignItems="center" gap={1}><Checkbox checked={chamada[a.id]==='PRESENTE'} disabled={!editavel} onChange={e=>setChamada(c=>({...c,[a.id]:e.target.checked?'PRESENTE':'AUSENTE'}))}/><Typography>{a.nome}</Typography>{a.registroAnterior&&<Chip size="small" variant="outlined" label="Registro anterior" />}</Box>)}<TextField label="Visitantes" type="number" value={visitantes} disabled={!editavel} onChange={e=>setVisitantes(Math.max(0,Number(e.target.value)))} inputProps={{min:0}}/><Button variant="contained" disabled={!editavel||carregando} onClick={salvar}>Salvar chamada</Button></Stack></CardContent></Card>}
 </Stack>
}
function mensagem(e:unknown){return e instanceof ApiError?e.message:'Não foi possível concluir a operação.'}
