import { Alert, Box, Button, Chip, CircularProgress, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import ReactECharts from 'echarts-for-react'
import { useEffect, useMemo, useState } from 'react'
import { painelApi, type DiscipuladoPainel, type EvolucaoMensal, type PainelGerenciaResponse, type ResumoPainel } from './painelApi'

const iso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const periodoPadrao = () => { const fim = new Date(); const mes = fim.getMonth() - 6; const ultimoDia = new Date(fim.getFullYear(), mes + 1, 0).getDate(); return { inicio: iso(new Date(fim.getFullYear(), mes, Math.min(fim.getDate(), ultimoDia))), fim: iso(fim) } }
const pct = (valor: number) => `${valor.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}%`

export default function ManagerDashboard() {
  const inicial = periodoPadrao()
  const [dataInicio, setDataInicio] = useState(inicial.inicio)
  const [dataFim, setDataFim] = useState(inicial.fim)
  const [periodo, setPeriodo] = useState(inicial)
  const [dados, setDados] = useState<PainelGerenciaResponse>()
  const [selecionadoId, setSelecionadoId] = useState(0)
  const [carregando, setCarregando] = useState(true)
  const [erro, setErro] = useState('')
  useEffect(() => { let ativo = true; setCarregando(true); setErro(''); painelApi.consultarGerencia(periodo.inicio, periodo.fim).then((resposta) => { if (!ativo) return; setDados(resposta); const preferido = resposta.discipulados.find((item) => item.ativo) ?? resposta.discipulados[0]; setSelecionadoId(preferido?.id ?? 0) }).catch((error: Error) => { if (ativo) { setDados(undefined); setErro(error.message) } }).finally(() => { if (ativo) setCarregando(false) }); return () => { ativo = false } }, [periodo])
  const selecionado = useMemo(() => dados?.discipulados.find((item) => item.id === selecionadoId), [dados, selecionadoId])
  return <Stack spacing={3}>
    <Box><Typography variant="h4">Minha gerência</Typography><Typography color="text.secondary">{dados?.gerencia.nome ?? 'Acompanhamento dos discipulados sob sua gerência.'}</Typography></Box>
    <Paper component="form" onSubmit={(event) => { event.preventDefault(); setPeriodo({ inicio: dataInicio, fim: dataFim }) }} sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField required label="Data inicial" type="date" value={dataInicio} onChange={(e) => setDataInicio(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField required label="Data final" type="date" value={dataFim} onChange={(e) => setDataFim(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><Button type="submit" variant="contained">Aplicar</Button></Stack></Paper>
    {carregando && <Box role="status" sx={{ py: 8, textAlign: 'center' }}><CircularProgress /><Typography>Carregando painel...</Typography></Box>}
    {erro && <Alert severity="error">{erro}</Alert>}
    {!carregando && dados && <><Kpis resumo={dados.resumo} />{dados.resumo.presentes + dados.resumo.ausentes + dados.resumo.visitantes === 0 && <Alert severity="info">Não há registros de frequência no período selecionado.</Alert>}<Serie titulo="Evolução mensal da gerência" dados={dados.evolucao} /><TabelaEvolucao titulo="Resumo mensal da gerência" dados={dados.evolucao} />
      {dados.discipulados.length === 0 ? <Alert severity="info">Não há discipulados com histórico no período.</Alert> : <><GraficoComparacao dados={dados.discipulados} /><TabelaComparacao dados={dados.discipulados} /><FormControl sx={{ maxWidth: 460 }}><InputLabel id="discipulado-painel-label">Discipulado</InputLabel><Select labelId="discipulado-painel-label" value={selecionadoId || ''} label="Discipulado" onChange={(e) => setSelecionadoId(Number(e.target.value))}>{dados.discipulados.map((item) => <MenuItem value={item.id} key={item.id}>{item.nome}{item.ativo ? '' : ' (inativo)'}</MenuItem>)}</Select></FormControl>{selecionado && <Detalhe discipulado={selecionado} />}</>}
    </>}
  </Stack>
}

function Kpis({ resumo }: { resumo: ResumoPainel }) { const itens: Array<[string, string | number]> = [['Presentes', resumo.presentes], ['Ausentes', resumo.ausentes], ['Visitantes', resumo.visitantes], ['Encontros', resumo.encontrosRealizados], ['Presença', pct(resumo.percentualPresenca)]]; return <Box sx={{ display: 'grid', gap: 2, gridTemplateColumns: { xs: '1fr', sm: 'repeat(2,1fr)', md: 'repeat(5,1fr)' } }}>{itens.map(([nome, valor]) => <Paper key={nome} sx={{ p: 2 }}><Typography color="text.secondary">{nome}</Typography><Typography variant="h5">{valor}</Typography></Paper>)}</Box> }
function Serie({ titulo, dados }: { titulo: string; dados: EvolucaoMensal[] }) { return <Paper sx={{ p: 2 }}><Typography variant="h6">{titulo}</Typography><ReactECharts style={{ height: 340 }} option={{ tooltip: { trigger: 'axis' }, legend: { data: ['Presentes', 'Ausentes', 'Visitantes'] }, xAxis: { type: 'category', data: dados.map((i) => i.referencia) }, yAxis: { type: 'value' }, series: [{ name: 'Presentes', type: 'line', data: dados.map((i) => i.presentes) }, { name: 'Ausentes', type: 'line', data: dados.map((i) => i.ausentes) }, { name: 'Visitantes', type: 'line', data: dados.map((i) => i.visitantes) }] }} /></Paper> }
function GraficoComparacao({ dados }: { dados: DiscipuladoPainel[] }) { return <Paper sx={{ p: 2 }}><Typography variant="h6">Presença por discipulado</Typography><ReactECharts style={{ height: Math.max(300, dados.length * 45) }} option={{ tooltip: { trigger: 'axis', valueFormatter: (v: number) => pct(v) }, xAxis: { type: 'value', max: 100, axisLabel: { formatter: '{value}%' } }, yAxis: { type: 'category', data: dados.map((i) => i.nome) }, series: [{ type: 'bar', name: 'Presença', data: dados.map((i) => i.resumo.percentualPresenca) }] }} /></Paper> }
function Detalhe({ discipulado }: { discipulado: DiscipuladoPainel }) { return <Stack spacing={2}><Stack direction="row" spacing={1} alignItems="center"><Typography variant="h5">{discipulado.nome}</Typography>{!discipulado.ativo && <Chip color="warning" label="Inativo" size="small" />}</Stack><Kpis resumo={discipulado.resumo} /><Serie titulo="Evolução mensal do discipulado" dados={discipulado.evolucao} /><TabelaEvolucao titulo="Histórico mensal do discipulado" dados={discipulado.evolucao} /></Stack> }
function TabelaEvolucao({ titulo, dados }: { titulo: string; dados: EvolucaoMensal[] }) { return <TableContainer component={Paper}><Typography variant="h6" sx={{ p: 2 }}>{titulo}</Typography><Table size="small"><TableHead><TableRow><TableCell>Mês</TableCell><TableCell>Presentes</TableCell><TableCell>Ausentes</TableCell><TableCell>Visitantes</TableCell><TableCell>Presença</TableCell></TableRow></TableHead><TableBody>{dados.map((i) => <TableRow key={i.referencia}><TableCell>{i.referencia}</TableCell><TableCell>{i.presentes}</TableCell><TableCell>{i.ausentes}</TableCell><TableCell>{i.visitantes}</TableCell><TableCell>{pct(i.percentualPresenca)}</TableCell></TableRow>)}</TableBody></Table></TableContainer> }
function TabelaComparacao({ dados }: { dados: DiscipuladoPainel[] }) { return <TableContainer component={Paper}><Typography variant="h6" sx={{ p: 2 }}>Resumo por discipulado</Typography><Table size="small"><TableHead><TableRow><TableCell>Discipulado</TableCell><TableCell>Presentes</TableCell><TableCell>Ausentes</TableCell><TableCell>Presença</TableCell></TableRow></TableHead><TableBody>{dados.map((i) => <TableRow key={i.id}><TableCell>{i.nome}{!i.ativo && ' (inativo)'}</TableCell><TableCell>{i.resumo.presentes}</TableCell><TableCell>{i.resumo.ausentes}</TableCell><TableCell>{pct(i.resumo.percentualPresenca)}</TableCell></TableRow>)}</TableBody></Table></TableContainer> }
